---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Aboulbox:
    - Caddy:
        icon: sh-caddy.svg
        server: my-docker
        container: caddy
        showStats: true
        widget:
          type: caddy
          url: http://caddy:2019
    - Frontend:
        icon: https://aboulbox.com/favicon.svg
        server: my-docker
        container: frontend
        href: https://aboulbox.com/
    - Backend:
        icon: https://aboulbox.com/favicon.svg
        server: my-docker
        container: backend
    - Umami:
        icon: sh-umami-light.svg
        server: my-docker
        container: umami
        href: https://umami.aboulbox.com/
    - Docusaurus:
        icon: sh-wikipedia-light.svg
        server: my-docker
        container: docusaurus
        href: https://wiki.aboulbox.com/
    - Immich:
        icon: sh-immich-light.svg
        server: my-docker
        container: immich
        href: https://photo.aboulbox.com/
        showStats: true
    - Database:
        icon: sh-postgresql-light.svg
        server: my-docker
        container: db

- For coding:
    - Github:
        icon: sh-github-light.svg
        href: https://github.com/aboul
    - Digital Ocean:
        icon: sh-digitalocean-light.svg
        href: https://cloud.digitalocean.com/droplets
    - Gandi domains:
        icon: sh-gandi-light.svg
        href: https://admin.gandi.net/domain/
    - Mailgun:
        icon: si-mailgun-#ffffff
        href: https://app.eu.mailgun.com/
    - ChatGPT:
        icon: sh-chatgpt-light.svg
        href: https://chatgpt.com/
    - Netlify:
        icon: sh-netlify-light.svg
        href: https://app.netlify.com/teams/aboul/sites

- Du social:
    - Discord:
        icon: sh-discord-light.svg
        href: https://discord.com/channels/
    - Youtube channel:
        icon: sh-youtube-light.svg
        href: https://www.youtube.com/@abelbrien
    - Facebook:
        icon: sh-facebook-light.svg
        href: https://facebook.com
    - Reddit:
        icon: sh-reddit-light.svg
        href: https://www.reddit.com/r/francenew
    - Instagram:
        icon: sh-instagram-light.svg
        href: https://www.instagram.com/

- Nice self-hosted repos:
    - Self-hosted awesome:
        href: https://github.com/awesome-selfhosted/awesome-selfhosted
    - Self-hosted Sysadmin:
        href: https://github.com/awesome-foss/awesome-sysadmin
    - Awesome Datasets:
        href: hhttps://github.com/awesomedata/awesome-public-datasets

- Icons for Services:
    - Dashboard icons:
        icon: dashboard-icons-dark.svg
        href: https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md
    - Font Awesome v6:
        icon: si-fontawesome-#ffffff
        href: https://fontawesome.com/v6/icons
    - Selfh.st:
        icon: sh-selfh-st-light.svg
        href: https://selfh.st/icons/
    - Material Design Icons:
        icon: si-materialdesignicons-#ffffff
        href: https://pictogrammers.com/library/mdi
    - Simple Icons:
        icon: si-simpleicons-#ffffff
        href: https://simpleicons.org
    - ðŸ˜‹ðŸ˜‹ EmojiPedia:
        href: https://emojipedia.org

- Config Helpers:
    - JSON Schema Example:
        href: https://json-schema.app/view/%23?url=https%3A%2F%2Fjson.schemastore.org%2Fpackage
    - JSON Config Validator:
        href: https://www.jsonschemavalidator.net/s/JFUj7X9J
    - JSON to YAML:
        href: https://jsonformatter.org/json-to-yaml
    - YAML to JSON:
        href: https://jsonformatter.org/yaml-to-json
