---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- glances:
    url: http://glances:61208
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cputemp: true # disabled by default
    uptime: true # disabled by default
    disk: 
        - /rootfs
        - /ssd  
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    expanded: true # show the expanded view

- search:
    provider: [brave, google]
    target: _blank

- openmeteo:
    label: Toulouse # optional
    latitude: 43.408944
    longitude: 1.468473
    timezone: Europe/Paris # optional
    units: metric # or imperial
    cache: 60 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
        maximumFractionDigits: 1

- datetime:
    locale: fr
    text_size: 3xl
    format:
        dateStyle: short
        timeStyle: short