services:
  navidrome:
    image: deluan/navidrome:0.60.2
    container_name: navidrome
    restart: unless-stopped
    environment:
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      - ND_EXTAUTH_TRUSTEDSOURCES=${ND_EXTAUTH_TRUSTEDSOURCES}
      - ND_PLUGINS_ENABLED=true
      - ND_PLUGINS_AUTORELOAD=true
      - ND_AGENTS=audiomuseai
    volumes:
      - ${ND_STORAGE_MUSIC}:/music:ro
      - ${ND_STORAGE_DATA}:/data
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    driver: bridge
    name: caddy_proxy-network
