services:
  docusaurus:
    image: node:lts-alpine
    container_name: docusaurus
    working_dir: /app
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DEBUG: search-local:*
    volumes:
      - ./wiki:/app
    networks:
      - proxy-network
    command: sh -c "npm install && npm run start -- --host 0.0.0.0 --poll 1000"

networks:
  proxy-network:
    external: true
    driver: bridge
    name: caddy_proxy-network
