services:
  caddy:
    environment:
      CADDY_GLOBAL_OPTIONS: |
        grace_period 10s
        default_sni ${SERVER_NAME}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/log/caddy:/var/log/caddy
      - aboulbox-dist:/srv/site:ro
      - ../../docs/docusaurus/wiki/dist:/srv/docs:ro
      - ${FILES_STORAGE_DATA}:/srv/files:ro

volumes: 
  aboulbox-dist:
    external: true